# permissions for end users to view loadgenerators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: loadgenerator-viewer-role
rules:
- apiGroups:
  - microsim.isala.me
  resources:
  - loadgenerators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - microsim.isala.me
  resources:
  - loadgenerators/status
  verbs:
  - get
