apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: microsim
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: microsim
subjects:
  - kind: ServiceAccount
    name: microsim
    namespace: microsim
