
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - microsim.isala.me
  resources:
  - simulations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - microsim.isala.me
  resources:
  - simulations/finalizers
  verbs:
  - update
- apiGroups:
  - microsim.isala.me
  resources:
  - simulations/status
  verbs:
  - get
  - patch
  - update
