# permissions for end users to edit simulations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: simulation-editor-role
rules:
- apiGroups:
  - microsim.isala.me
  resources:
  - simulations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - microsim.isala.me
  resources:
  - simulations/status
  verbs:
  - get
