apiVersion: microsim.isala.me/v1alpha1
kind: LoadGenerator
metadata:
    name: loadgenerator-sample
spec:
    requests:
        - |
            {
                "designation": "service_1",
                "probability": 100,
                "faults": {
                    "before": [{"type": "latency", "args": { "delay": 600 }}],
                    "after": [{"type": "latency", "args": { "delay": 600 }}]
                },
                "routes": [
                    {
                        "designation": "service_2",
                        "probability": 100,
                        "faults": {
                            "before": [{"type": "latency", "args": { "delay": 600 }}],
                            "after": [{"type": "latency", "args": { "delay": 600 }}]
                        },
                        "routes": [
                            {
                                "designation": "service_3",
                                "probability": 100,
                                "faults": {
                                    "before": [{"type": "latency", "args": { "delay": 600 }}],
                                    "after": [{"type": "latency", "args": { "delay": 600 }}]
                                },
                                "routes": [
                                    {
                                        "designation": "service_4",
                                        "probability": 100,
                                        "faults": {
                                            "before": [{"type": "latency", "args": { "delay": 600 }}],
                                            "after": [{"type": "latency", "args": { "delay": 600 }}]
                                        },
                                        "routes": null
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
    simulationRef:
        name: simulation-sample
        namespace: default
    requestCount: 1
    replicas: 1
    #  timeout: 15m
    betweenDelay: 10s
