apiVersion: microsim.isala.me/v1alpha1
kind: LoadGenerator
metadata:
  name: loadgenerator-sample
spec:
  request: |
    {
      "designation": "service_1",
      "faults": {
        "before": [
          {
            "type": "latency",
            "args": {
              "delay": 600
            }
          }
        ],
        "after": [
          {
            "type": "memory-leak",
            "args": {
              "size": 250,
              "duration": 10000
            }
          }
        ]
      },
      "routes": [
        {
          "designation": "service_2",
          "faults": {
            "before": [],
            "after": [
              {
                "type": "latency",
                "args": {
                  "delay": 600
                }
              }
            ]
          },
          "routes": [
            {
              "designation": "service_4",
              "faults": {
                "before": [
                  {
                    "type": "latency",
                    "args": {
                      "delay": 200
                    }
                  }
                ],
                "after": []
              }
            }
          ]
        },
        {
          "designation": "service_3",
          "faults": {
            "before": [
              {
                "type": "latency",
                "args": {
                  "delay": 1000
                }
              }
            ],
            "after": []
          }
        }
      ]
    }
  simulationRef:
    name: simulation-sample
    namespace: default
  requestCount: 10
#  timeout: 15m
  betweenDelay: 20s
